### ISSUE TITLE
Manifest fails format validation

### ISSUE THREAD

**Issue by ddka22** [edgeimpulse/edgeimpulse-ce-manifest#6]
The manifest needs to be tested against the mtb-manifest-checker for any issues before merging into the main pipeline. Please find the mtb-manifest-checker tool here: https://github.com/Infineon/mtb-manifest-checker

There are formatting issues with the merged manifest
```
########## test format ##########

[info] using python (3.8.5) at [/var/tmp/jenkins/workspace/periodic/bot_github/env/bin/python]

+ xmllint --format edgeimpulse/edgeimpulse-ce-manifest/raw/main/edgeimpulse-ce-manifest-fv2.xml | post-process with custom format

xmllint returned: 0
FATAL ERROR: formatting error:
39c39
<   </app>  
---
>   </app>

Manifest: edgeimpulse/edgeimpulse-ce-manifest/raw/main/edgeimpulse-ce-manifest-fv2.xml
failed format validation

####################
```

Additionally, please set the `tools_max_version to 2.4.1` for all fields that have `tools_min_version set as 2.4.0`. 

Please fix the issues at the earliest.

**Comment by faradayberry** [comment]
Sorry for the delay on this and for not using the manifest checker the first time. I cannot figure out why it has a formatting error on line 39 when I added the 2nd app following the guide here: 

https://documentation.infineon.com/html/psoc6/nks1667491588974.html

But I may have missed something? Thanks for the help!

**Comment by ddka22** [comment]
When you run the formatting test using the mtb-manifest-checker, you can find the formatted file in the "out" folder. You can replace what you have with the file in the "out" folder. 

It is difficult sometimes to figure out what affects the pylint program we use for formatting, so I would suggest using the manifest file generated in the "out" folder. Let me know if you have any trouble.
